name: First workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
       - name: Step 1
         run: echo 'Step 1 Complete!'
         
       - name: Step 2
         run: echo 'Step 2 Complete!'
