name: First workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
       - name: Step 1
         run: echo 'Step 1 Complete!'
         
       - name: Step 2
         run: echo 'Step 2 Complete!'

  job2:
    runs-on: ubuntu-latest
    needs: [ job1 ]
    steps:
      - name: Job 2 Step
        uses: mscoutermarsh/cowsays-action@v1
        with:
          # What does the cow say?
          text: Ready for prod–ship it!
          # Color of your cow
          color: magenta
        
